#!/bin/bash
sum=0
TMP1=./TMP1
echo -e "8\n7\n6" > $TMP1

while read num
do 
 echo "Trace: In Loop"
 echo "Trace: num: $num"
 sum=`expr $sum + $num`
 echo "Trace: sum: $sum"
 echo -e "Trace: End of loop\n"
done < $TMP1

