#!/bin/bash

#This script will act as a makefile for my adventures program
#compile  will just compile the one c file (at this time)
#compile -c will clear all compiled files
#compule -r will compile and run the program
file_name="smallsh"
test_file="test_program"
if [[ $# > "1" ]];
then	
	echo "too many arguments."
	echo "compile {-clear | -run} "
	echo ""
	exit 1
fi

if [[ $# = "0" ]];
then
	echo -e "Compile only\n"
	gcc -o $file_name $file_name.c
	gcc -o $test_file $test_file.c
	exit 1
fi

if [[ $1 == -c* ]];
then 
	echo -e "Clear \n"
	rm -f $file_name
	rm -f $test_file
	exit 1
elif [[ $1 == -r* ]];
then
	echo -e "Compile Run \n"
	gcc -o $file_name $file_name.c
	gcc -o $test_file $test_file.c
	if [[ $? = 0 ]];
    then
		clear
		$file_name
	fi
	exit 1
else
	echo "Invalid arguments..."
	echo "compile {-clear | -run} "
	exit 1
fi
